name = "daniel-sinambela-portfolio"
compatibility_date = "2026-06-20"
pages_build_output_dir = "."

[[d1_databases]]
binding = "PORTFOLIO_DB"
database_name = "portfolio_daniel"
database_id = "replace-with-your-d1-database-id"
